Repository yearn/yearn-meta, pull requests merged in 2022-03, with the labels that each got.

#179 feat: add new strategies
  data/strategies/1/AaveLenderOptimizer.json
  data/strategies/1/NotionalReinvest.json
  data/strategies/250/BeethovenSingleSided.json
  data/strategies/250/GeistFolding.json
  data/strategies/250/SolidexJointProvider.json
  data/strategies/250/SolidexSingleSidedStable.json
  data/strategies/250/SolidexSingleSidedVolatile.json
Labels: enhancement

#181 fix: run localization script
  data/strategies/250/SolidexJointProvider.json
  data/strategies/250/SolidexSingleSidedStable.json
Labels: enhancement

#183 translation(protocol): 1inch
  data/protocols/1/1inch.json
Labels: translation

#193 translation(protocol): Balancer
  data/protocols/1/Balancer.json
Labels: translation

#196 translate(protocol): 250
  data/protocols/250/0xDAO.json
  data/protocols/250/Beethoven-x.json
  data/protocols/250/CurveFinance.json
  data/protocols/250/EsterFinance.json
  data/protocols/250/GeistFinance.json
  data/protocols/250/IronBank.json
  data/protocols/250/Scream.json
  data/protocols/250/SolidexFinance.json
  data/protocols/250/SpiritSwap.json
  data/protocols/250/Spookyswap.json
  data/protocols/250/Tarot.json
Labels: translation

#190 German translations
  data/protocols/250/0xDAO.json
  data/protocols/250/Beethoven-x.json
  data/protocols/250/CurveFinance.json
  data/protocols/250/EsterFinance.json
  data/protocols/250/GeistFinance.json
  data/protocols/250/IronBank.json
  data/protocols/250/Scream.json
  data/protocols/250/SolidexFinance.json
  data/protocols/250/SpiritSwap.json
  data/protocols/250/Spookyswap.json
  data/protocols/250/Tarot.json
  data/strategies/42161/CurveGauge.json
Labels: translation, translator needs to review

#197 zh translation
  data/protocols/1/1inch.json
Labels: translation, translation check

#203 Protocols edit
  data/protocols/1/1inch.json
  data/protocols/1/Aave.json
  data/protocols/1/AlphaHomora.json
  data/protocols/1/Balancer.json
  data/protocols/1/CompoundFinance.json
  data/protocols/1/ConvexFinance.json
  data/protocols/1/CreamFinance.json
  data/protocols/1/CurveFinance.json
  data/protocols/1/FiatDAO.json
  data/protocols/1/Hegic.json
  data/protocols/1/IdleFinance.json
  data/protocols/1/InverseFinance.json
  data/protocols/1/IronBank.json
  data/protocols/1/KeeperDAO.json
  data/protocols/1/LeagueDAO.json
  data/protocols/1/Liquity.json
  data/protocols/1/MakerDAO.json
  data/protocols/1/MushroomFinance.json
  data/protocols/1/NotionalFinance.json
  data/protocols/1/PoolTogether.json
  data/protocols/1/Sushi.json
  data/protocols/1/Synthetix.json
  data/protocols/1/Tokemak.json
  data/protocols/1/Universe.json
  data/protocols/1/VesperFinance.json
  data/protocols/1/dydx.json
Labels: translation

#204 fix: typos, edits, formatting in protocols, strategies, and vaults
  data/protocols/1/Balancer.json
  data/protocols/1/KeeperDAO.json
  data/protocols/1/Universe.json
  data/protocols/1/dydx.json
  data/protocols/250/IronBank.json
  data/protocols/250/Tarot.json
  data/strategies/250/BooXbooHec.json
  data/strategies/250/EsterReinvest.json
  data/tokens/1/0x0000000000085d4780B73119b644AE5ecd22b376.json
  data/tokens/1/0x5282a4eF67D9C33135340fB3289cc1711c13638C.json
  data/tokens/1/0x5f98805A4E8be255a32880FDeC7F6728C6568bA0.json
  data/tokens/1/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2.json
  data/tokens/1/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9.json
  data/tokens/1/0xC25a3A3b969415c80451098fa907EC722572917F.json
  data/tokens/250/0x0000000000000000000000000000000000000000.json
  data/tokens/250/0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83.json
  data/tokens/250/0x74b23882a30290451A17c44f4F05243b6b58C76d.json
  data/tokens/42161/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1.json
Labels: bug, enhancement

#205 protocols 250 translated to Chinese
  data/protocols/250/0xDAO.json
  data/protocols/250/Beethoven-x.json
  data/protocols/250/CurveFinance.json
  data/protocols/250/EsterFinance.json
  data/protocols/250/GeistFinance.json
  data/protocols/250/IronBank.json
  data/protocols/250/Scream.json
  data/protocols/250/SolidexFinance.json
  data/protocols/250/SpiritSwap.json
  data/protocols/250/Spookyswap.json
  data/protocols/250/Tarot.json
Labels: translation

#222 translate(protocol-1)(ES)
  data/protocols/1/1inch.json
  data/protocols/1/Aave.json
  data/protocols/1/AlphaHomora.json
  data/protocols/1/Balancer.json
  data/protocols/1/CompoundFinance.json
  data/protocols/1/ConvexFinance.json
  data/protocols/1/CreamFinance.json
  data/protocols/1/CurveFinance.json
  data/protocols/1/FiatDAO.json
  data/protocols/1/Hegic.json
  data/protocols/1/IdleFinance.json
  data/protocols/1/InverseFinance.json
  data/protocols/1/IronBank.json
  data/protocols/1/KeeperDAO.json
  data/protocols/1/LeagueDAO.json
  data/protocols/1/Liquity.json
  data/protocols/1/MakerDAO.json
  data/protocols/1/MushroomFinance.json
  data/protocols/1/NotionalFinance.json
  data/protocols/1/PoolTogether.json
  data/protocols/1/Sushi.json
  data/protocols/1/Synthetix.json
  data/protocols/1/Tokemak.json
  data/protocols/1/Universe.json
  data/protocols/1/VesperFinance.json
  data/protocols/1/dydx.json
Labels: translation

#221 translate(protocol-1)(Ja): Comp, Convex, Cream, Curve, Fiat, Hegic, Idle
  data/protocols/1/CompoundFinance.json
  data/protocols/1/ConvexFinance.json
  data/protocols/1/CreamFinance.json
  data/protocols/1/CurveFinance.json
  data/protocols/1/FiatDAO.json
  data/protocols/1/Hegic.json
  data/protocols/1/IdleFinance.json
Labels: translation

#202 Metadata 250 Spanish translation
  data/protocols/250/0xDAO.json
  data/protocols/250/Beethoven-x.json
  data/protocols/250/CurveFinance.json
  data/protocols/250/EsterFinance.json
  data/protocols/250/GeistFinance.json
  data/protocols/250/IronBank.json
  data/protocols/250/Scream.json
  data/protocols/250/SolidexFinance.json
  data/protocols/250/SpiritSwap.json
  data/protocols/250/Tarot.json
Labels: translation check

#226 Add French translation for [Protocols] folder
  data/protocols/1/1inch.json
  data/protocols/1/Aave.json
  data/protocols/1/AlphaHomora.json
  data/protocols/1/Balancer.json
  data/protocols/1/CompoundFinance.json
  data/protocols/1/ConvexFinance.json
  data/protocols/1/CreamFinance.json
  data/protocols/1/CurveFinance.json
  data/protocols/1/FiatDAO.json
  data/protocols/1/Hegic.json
  data/protocols/1/IdleFinance.json
  data/protocols/1/InverseFinance.json
  data/protocols/1/IronBank.json
  data/protocols/1/KeeperDAO.json
  data/protocols/1/LeagueDAO.json
  data/protocols/1/Liquity.json
  data/protocols/1/MakerDAO.json
  data/protocols/1/MushroomFinance.json
  data/protocols/1/NotionalFinance.json
  data/protocols/1/PoolTogether.json
  data/protocols/1/Sushi.json
  data/protocols/1/Synthetix.json
  data/protocols/1/Tokemak.json
  data/protocols/1/Universe.json
  data/protocols/1/VesperFinance.json
  data/protocols/1/dydx.json
  data/protocols/250/0xDAO.json
  data/protocols/250/Beethoven-x.json
  data/protocols/250/CurveFinance.json
  data/protocols/250/EsterFinance.json
  data/protocols/250/GeistFinance.json
  data/protocols/250/IronBank.json
  data/protocols/250/Scream.json
  data/protocols/250/SolidexFinance.json
  data/protocols/250/SpiritSwap.json
  data/protocols/250/Spookyswap.json
  data/protocols/250/Tarot.json
Labels: translation

#228 Yearn Meta - protocols spanish review
  data/protocols/1/1inch.json
  data/protocols/1/Aave.json
  data/protocols/1/CompoundFinance.json
  data/protocols/1/ConvexFinance.json
  data/protocols/1/CreamFinance.json
  data/protocols/1/FiatDAO.json
  data/protocols/1/Hegic.json
  data/protocols/1/IronBank.json
  data/protocols/1/Liquity.json
  data/protocols/1/Synthetix.json
  data/protocols/250/Beethoven-x.json
  data/protocols/250/CurveFinance.json
  data/protocols/250/IronBank.json
  data/protocols/250/Scream.json
  data/protocols/250/SpiritSwap.json
  data/protocols/250/Tarot.json
Labels: translation check

#219 Update LeagueDAO.json
  data/protocols/1/LeagueDAO.json
Labels: translation check

#218 Update Liquity.json
  data/protocols/1/Liquity.json
Labels: translation check

#217 Update MakerDAO.json
  data/protocols/1/MakerDAO.json
Labels: translation check

#216 Update MushroomFinance.json
  data/protocols/1/MushroomFinance.json
Labels: translation check

#215 Update NotionalFinance.json
  data/protocols/1/NotionalFinance.json
Labels: translation check

#214 Update PoolTogether.json
  data/protocols/1/PoolTogether.json
Labels: translation check

#213 Update Sushi.json
  data/protocols/1/Sushi.json
Labels: translation check

#212 Update Synthetix.json
  data/protocols/1/Synthetix.json
Labels: translation check

#211 Update Tokemak.json
  data/protocols/1/Tokemak.json
Labels: translation check

#210 Update Universe.json
  data/protocols/1/Universe.json
Labels: translation check

#207 Update FiatDAO.json
  data/protocols/1/FiatDAO.json
Labels: translation check

#206 Update InverseFinance.json
  data/protocols/1/InverseFinance.json
Labels: translation check

#180 fix: Three month description is inaccurate
  data/strategies/1/NotionalReinvest.json
Labels: enhancement
